In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import tree

In [2]:
df = pd.read_excel('database1.xlsx') #definir df
df

id             date    price  bedrooms  bathrooms  sqft_living  \
0    7237550310  20140512T000000  1230000         4       4.50         5420   
1    7203220400  20140707T000000   861990         5       2.75         3595   
2    8682281200  20150309T000000   479950         2       2.00         1510   
3    7202340400  20150303T000000   516500         3       2.50         1480   
4    7202360350  20140630T000000   780000         4       2.50         3500   
..          ...              ...      ...       ...        ...          ...   
400  8682320900  20141105T000000   580000         3       2.00         1870   
401  2413910120  20140702T000000   915000         3       4.50         3850   
402  8682291050  20140708T000000   810000         2       2.75         2700   
403  7237550100  20140825T000000  1410000         4       4.00         4920   
404  7202300110  20140915T000000   810000         4       3.00         3990   

     sqft_lot  floors  waterfront  view  ...  yr_built  yr_renovated  zipcode  \
0      101930     1.0           0     0  ...      2001             0    98053   
1        5639     2.0           0     0  ...      2014             0    98053   
2        6516     1.0           0     0  ...      2005             0    98053   
3        4729     2.0           0     0  ...      2004             0    98053   
4        7048     2.0           0     0  ...      2005             0    98053   
..        ...     ...         ...   ...  ...       ...           ...      ...   
400      5300     1.0           0     0  ...      2009             0    98053   
401     62726     2.0           0     0  ...      2013             0    98053   
402      8572     1.0           0     0  ...      2007             0    98053   
403     50621     2.0           0     0  ...      2012             0    98053   
404      7838     2.0           0     0  ...      2003             0    98053   

         lat       long  sqft_living15  sqft_lot15         PPA    zscore  CARO  
0    47.6561 -122005.00           4760      101930  226.937269 -0.739317     0  
1    47.6848 -122016.00           3625        5639  239.774687 -0.516311     1  
2    47.7076 -122013.00           1640        6009  317.847682  0.839935     2  
3    47.6794 -122034.00           2250        4729  348.986486  1.380864     2  
4    47.6811 -122025.00           3920        7864  222.857143 -0.810195     0  
..       ...        ...            ...         ...         ...       ...   ...  
400  47.7106    -122.02           1870        5050  310.160428  0.706396     2  
401  47.6735 -122058.00           2630       46609  237.662338 -0.553006     1  
402  47.7236 -122033.00           2680        8569  300.000000  0.529894     2  
403  47.6575 -122006.00           4920       74052  286.585366  0.296861     1  
404  47.6857 -122046.00           3370        6814  203.007519 -1.155013     0  

[405 rows x 24 columns]

In [3]:
#def treino/teste
df_sem_10_ult = df.head(len(df)-10) #parcela de treino
df_10_ult = df.tail(10) #parcerla de teste

In [136]:
#definir X e y train
X_train = df_sem_10_ult.drop(['id', 'yr_built', 'floors', 'sqft_lot', 'sqft_living', 'grade', 'date', 'CARO', 'sqft_above', 'sqft_basement', 'yr_renovated', 'view', 'price', 'PPA', 'zscore', 'sqft_living15', 'sqft_lot15', 'waterfront', 'lat', 'long', 
             'zipcode'], axis=1)
y_train = df_sem_10_ult['CARO']

decision_tree = tree.DecisionTreeClassifier(max_depth = 7)
decision_tree.fit(X_train, y_train)

#gerar arvore png
with open("chatbot.dot", 'w') as f: 
     f = tree.export_graphviz(decision_tree,
                              out_file=f,
                              max_depth = 7,
                              impurity = True,
                              feature_names = list(df_sem_10_ult.drop(['id', 'floors', 'sqft_lot', 'sqft_living', 'yr_built', 'grade', 'date', 'CARO', 'sqft_above', 'sqft_basement', 'yr_renovated', 'view', 'price', 'PPA', 'zscore', 'sqft_living15', 'sqft_lot15', 'waterfront', 'lat', 'long', 
             'zipcode'], axis=1)),
                              class_names = ['0', '1', '2'],
                              rounded = True,
                              filled= True )

In [137]:
#definir x e y teste
X_teste = df_10_ult.drop(['id', 'grade', 'floors', 'sqft_lot', 'sqft_living', 'yr_built', 'date', 'CARO', 'sqft_above', 'sqft_basement', 'yr_renovated', 'view', 'price', 'PPA', 'zscore', 'sqft_living15', 'sqft_lot15', 'waterfront', 'lat', 'long', 
             'zipcode'], axis=1)
y_teste= df_10_ult['CARO']

In [138]:
pred = decision_tree.predict(X_teste)

#precisão
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_teste, pred))
print("\n")
print(classification_report(y_teste, pred))



[[2 0 0]
 [0 6 0]
 [0 1 1]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       0.86      1.00      0.92         6
           2       1.00      0.50      0.67         2

    accuracy                           0.90        10
   macro avg       0.95      0.83      0.86        10
weighted avg       0.91      0.90      0.89        10



In [ ]:
##implementação chatbot

#def classe
class Tree():
    def __init__(self):
        pass

    def ask_question(self):
        return self.question

    def check_answer(self,answer):
        if answer == self.answerTrue:
            return self.leftNode
        elif answer == self.answerFalse:
            return self.rightNode
        else:
            return False

texto = pd.read_csv("chatbase.csv", sep=',', index_col="ID")

#montar arvore
def rec_build_tree(linha):
    row = texto.loc[linha]
    if row["Pergunta"] == "NÓ FOLHA":
        return row["A"]
    node = Tree() 
    node.leftNode = rec_build_tree(int(row["Nó A"]))    
    node.rightNode = rec_build_tree(int(row["Nó B"]))
    node.question = row["Pergunta"]
    node.answerTrue = row["A"]
    node.answerFalse = row["B"]
    return node

def is_obj(obj):
    return False if type(obj).__name__ == "str" else True

counter_tickets = 0
while True:
    arvore = rec_build_tree(1)
    count_erros=0
    while True:
        if count_erros == 2:
            print("ERROS SUCESSIVOS\nVERIFIQUE AS OPÇÕES ANTES DE TENTAR NOVAMENTE\n")
            print("\nMuitas informações! :/ \nPor favor me reinicie.")
            break
        opcoes = {1:arvore.answerTrue,2:arvore.answerFalse}
        print("\nEscolha uma das opções abaixo:"+"\n0 para sair"+"\n1 para "+opcoes[1]+"\n2 para "+opcoes[2]+"\n")
        response = input(arvore.ask_question())
        while not response.isnumeric():
            if count_erros == 2:
                print("\nMuitas informações! :/ \nPor favor me reinicie.")
                sys.exit()
            print("\nMe desculpe, não conheço essa opção, vamos tentar novamente? :)\n")
            print("Escolha uma das opções abaixo:"+"\n0 para sair"+"\n1 para "+opcoes[1]+"\n2 para "+opcoes[2])
            response = input(arvore.ask_question())
            count_erros+=1
            
        if int(response) == 0:
            print("\nFim.\n")
            sys.exit()
            
        question = opcoes[int(response)]
        answer = arvore.check_answer(question)
        if answer == False:
            print("\nMe desculpe, não conheço essa opção, vamos tentar novamente? :)")
            count_erros+=1
        elif not is_obj(answer):
            break
        else:
            arvore = answer 
            
    print(answer)
                
    print("-------------------------------------")


Escolha uma das opções abaixo:
0 para sair
1 para  SIM
2 para NÃO

